# Generated by Django 6.0.3 on 2026-03-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Tech", "Tech"),
                    ("Lifestyle", "Lifestyle"),
                    ("Travel", "Travel"),
                    ("Food", "Food"),
                    ("Education", "Education"),
                    ("Health", "Health"),
                    ("Entertainment", "Entertainment"),
                    ("Business", "Business"),
                    ("Sports", "Sports"),
                    ("Other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
