# Generated by Django 6.0.3 on 2026-03-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_post_category_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="isBookmarked",
            field=models.BooleanField(default=False),
        ),
    ]
