# Generated by Django 6.0.3 on 2026-03-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_post_isbookmarked"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="commentCount",
            field=models.IntegerField(default=0),
        ),
    ]
