# Generated by Django 6.0.3 on 2026-03-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
